import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const ctx=vm.createContext({window:{},Date});
for(const name of ['data','context','priorities','actions','commercial'])vm.runInContext(readFileSync(`dist/${name}.js`,'utf8'),ctx);
const D=ctx.window.COMPASS_DATA,Q=ctx.window.CompassPriority;
const a={...D.accounts.find(a=>a.id==='A04144'),review:null,review_date:null,late_rate:0,drops:[],recency:20,cadence:10};
const assess=x=>Q.assess(x,D.asof);
let q=assess(a);assert.equal(q.weight,1);assert.equal(q.annualValueAtRisk,a.exposed*12);assert.equal(q.annualValue,a.baseline*12);
q=assess({...a,review:2,review_date:'2018-08-22'});assert.equal(q.weight,1.25);assert.equal(q.primaryDriver,'service');
assert.equal(assess({...a,review:2,review_date:'2018-03-01'}).weight,1,'Old ratings do not receive a recent-issue boost');
assert.equal(assess({...a,review:2,review_date:'2018-09-01'}).weight,1,'Future ratings excluded');
assert.equal(assess({...a,review:2,review_date:null}).weight,1,'Undated review does not establish freshness');
assert.equal(assess({...a,review:4,review_date:'2018-08-22'}).weight,1,'A good recent average does not count as a bad review');
assert.equal(assess({...a,late_rate:0.01}).weight,1.25);
const drop={category:'beverages',previous_orders:4,last:'2018-05-02'};
q=assess({...a,review:1,review_date:'2018-08-22',late_rate:0.5,drops:[drop]});assert.equal(q.weight,1.25,'OR conditions boost once, not three times');assert.equal(q.signals.length,3);
assert.equal(assess({...a,recency:40}).weight,1,'Strictly beyond four usual gaps');
assert.equal(assess({...a,recency:41}).weight,0.6);
assert.equal(assess({...a,recency:41,late_rate:0.1}).weight,0.75,'Issue and silence adjustments combine');
assert.equal(assess({...a,recency:90}).eligible,false,'Prevention and win-back remain separate');
assert.equal(Q.assess({...a,late_rate:.2,recency:41},D.asof,{issueBoost:1,silencePenalty:1,silenceGaps:4}).weight,1);
for(const p of [{issueBoost:0,silencePenalty:.6,silenceGaps:4},{issueBoost:1.25,silencePenalty:1.5,silenceGaps:4},{issueBoost:1.25,silencePenalty:.6,silenceGaps:0}])assert.throws(()=>Q.validate(p));
const yearly=D.accounts.slice().sort((a,b)=>a.exposed*12-b.exposed*12||a.id.localeCompare(b.id)).map(a=>a.id);
const monthly=D.accounts.slice().sort((a,b)=>a.exposed-b.exposed||a.id.localeCompare(b.id)).map(a=>a.id);assert.deepEqual(yearly,monthly,'Annualisation alone preserves order');
for(const account of D.accounts){const p=assess(account);assert.ok(Number.isFinite(p.score)&&p.weight>0);assert.equal(p.annualValueAtRisk,account.exposed*12);}
const categoryAccount={...a,drops:[drop]},oldComments={issues:{[a.id]:[{tag:'Wrong / missing item',count:1,first:'2018-03-01',last:'2018-03-01'}]}};
const categoryInputs=Q.adviceInputs(categoryAccount,oldComments,assess(categoryAccount),D.asof);
assert.equal(ctx.window.CompassCommercial.build(categoryInputs.account,categoryInputs.context).kind,'basket','Ranked category gap receives a matching basket remedy');
assert.equal(oldComments.issues[a.id].length,1,'Underlying evidence is preserved');
const lateAccount={...a,late_rate:0.05,reasons:[]},lateInputs=Q.adviceInputs(lateAccount,{},assess(lateAccount),D.asof);
assert.equal(ctx.window.CompassCommercial.build(lateInputs.account,lateInputs.context).kind,'service','Even a late rate below the old warning badge threshold gets a service remedy');
const eligible=D.accounts.filter(a=>a.state==='SP'&&assess(a).eligible).sort((a,b)=>assess(b).score-assess(a).score).slice(0,6);
assert.ok(eligible.some(a=>a.id==='A04144'));assert.ok(eligible.some(a=>a.risk<.3));
console.log('PASS: annualisation preserves base order, recent evidence rules, one-time issue boost, combined penalties, editable boundaries, remedy alignment and low-risk high-value eligibility.');
