import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const elements=new Map(), registered=[];
const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',open:false,classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll:()=>[],showModal(){this.open=true;},close(){this.open=false;}});return elements.get(id);};
const context=vm.createContext({console,Intl,Date,Set,AbortController,TextEncoder,window:{scrollTo(){},addEventListener(){}},document:{getElementById:element,querySelectorAll:()=>[],modelContext:{registerTool:t=>registered.push(t)}},setTimeout:()=>0,clearTimeout(){}});
for(const f of ['dist/data.js','dist/priorities.js','dist/actions.js','dist/commercial.js','dist/app.js'])vm.runInContext(readFileSync(f,'utf8'),context,{filename:f});
const run=s=>vm.runInContext(s,context);
assert.equal(run('D.accounts.length'),2583);
assert.equal(run('selected().length'),6);
assert.ok(run('selected().every(a=>a.recency<90 && a.state===state.territory)'));
assert.ok(run('selected().some(a=>a.id==="A04144"&&a.risk<.3)'));
assert.ok(run('selected().every((a,i,arr)=>!i || priorityFor(arr[i-1]).score>=priorityFor(a).score)'));
run('approve();approve()');assert.equal(run('state.events.length'),6);
run('propose();approve()');assert.equal(run('state.events.length'),12);
assert.equal(run('new Set(state.events.map(e=>e.date+e.time)).size'),12);
assert.equal(run('new Set(state.events.map(e=>e.id)).size'),12);
run('state.capacity=20;propose();approve()');assert.ok(run('state.events.length<=20'));
run('state.events[0].follow="2018-09-10";state.events[0].note="Check stock, then reorder; agreed"');
const rawIcs=run('calendarText()');
assert.ok(rawIcs.split('\r\n').every(line=>new TextEncoder().encode(line).length<=75));
const ics=rawIcs.replace(/\r\n /g,'');
assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,run('state.events.length+1'));
assert.ok(ics.includes('DTSTART:20180910T100000'));
assert.ok(ics.includes('Check stock\\, then reorder\\; agreed'));
assert.throws(()=>run('openAccount("invalid")'),/Unknown account/);
assert.equal(registered.length,2);
assert.ok(registered[0].execute().accounts.length>0);
assert.throws(()=>registered[1].execute({accountId:'invalid'}),/Unknown accountId/);
assert.equal(registered[1].execute({accountId:run('D.accounts[0].id')}).opened,true);
assert.ok(run('D.accounts.every(a=>a.risk>=0 && a.risk<=1 && Number.isFinite(a.exposed))'));
assert.ok(!readFileSync('dist/data.js','utf8').includes('customer_id'));
console.log('PASS: real scores, priority, approval idempotency, schedule uniqueness, follow-up calendar, evidence and agent tool validation.');
